package com.mycompany.java.crud;

import Acceso_Datos.EmpleadoDAL;
import Acceso_Datos.ProyectoDAL;
import Entidades.Empleado;
import Entidades.Proyecto;
import Utilerias.OpcionesCRUD;
import static Utilerias.OpcionesCRUD.CREAR;
import static Utilerias.OpcionesCRUD.EDITAR;
import static Utilerias.OpcionesCRUD.ELIMINAR;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class Form_Proyecto extends javax.swing.JFrame {

    // ATRIBUTOS:
    private OpcionesCRUD opcionesCRUD;
    private Proyecto ProyectoActual;
    // Lista De Categorias
    private HashMap<Integer, Empleado> Registros_Empleados = new HashMap<Integer, Empleado>();

    
    
    // CONSTRUCTOR:
    public Form_Proyecto(OpcionesCRUD opcion, Proyecto proyecto) {
        // Opcion A Realizar:
        opcionesCRUD = opcion;
        initComponents();

        //Obtenemos Todos Los Registros Tabla Categorias:
        ArrayList<Empleado> Objetos_Obtenidos = EmpleadoDAL.ObtenerTodos();

        // Agrupamos Los Registros Por Nombres:
        DefaultComboBoxModel<Empleado> RegistroCombo = new DefaultComboBoxModel(Objetos_Obtenidos.toArray());

        // Agregamos Cada Categoria A Una Estructura
        for (Empleado Registro : Objetos_Obtenidos) {
            Registros_Empleados.put(Registro.getEmpleadoID(), Registro);
        }

        // Mandamos al ComboBox Del Formulario Los Registros De Categoria
        TxtEMPLEADOS.setModel(RegistroCombo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNOMBRE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDESCRIPCION = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TxtFechaFin = new com.toedter.calendar.JDateChooser();
        TxtFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtEMPLEADOS = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        BtnCANCELAR = new javax.swing.JButton();
        BtnGUARDAR = new javax.swing.JButton();

        jLabel1.setText("DATOS    DEL    PROYECTO");

        jLabel2.setText("NOMBRE:");

        TxtDESCRIPCION.setColumns(20);
        TxtDESCRIPCION.setRows(5);
        jScrollPane1.setViewportView(TxtDESCRIPCION);

        jLabel3.setText("DESCRIPCION:");

        jLabel4.setText("Fecha De Inicio:");

        jLabel5.setText("Fecha De Fin:");

        jLabel6.setText("Empleado A Cargo:");

        BtnCANCELAR.setText("CANCELAR");
        BtnCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCANCELARActionPerformed(evt);
            }
        });

        BtnGUARDAR.setText("GUARDAR");
        BtnGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGUARDARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(TxtNOMBRE)
                            .addComponent(TxtEMPLEADOS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtFechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(TxtFechaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(BtnGUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TxtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TxtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEMPLEADOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*                      EVENTOS DE BOTONES
    *********************************************************************/

    private void BtnGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGUARDARActionPerformed

        if (opcionesCRUD != null) {
            switch (opcionesCRUD) {
                case CREAR:
                    CrearRegistro();
                    this.setVisible(false);
                    break;

                case EDITAR:
                    //EditarRegistro();
                    this.setVisible(false);
                    break;

                case ELIMINAR:
                    //EliminarRegistro();
                    this.setVisible(false);
                    break;

                default:
                    break;
            }
        }
    }//GEN-LAST:event_BtnGUARDARActionPerformed

    private void BtnCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCANCELARActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BtnCANCELARActionPerformed

    /*                    METODO REALIZAR CAMBIOS EN DB
    *********************************************************************/
    // OBTIENE LOS ATRIBUTOS DEL FORMULARIO Y CREAR UN OBJETO DE ELLOS
    private Proyecto DatosDelFormulario() {
        
        // Objeto:
        Proyecto proyecto = new Proyecto();

        // Datos Del Formulario:
        String nombre = TxtNOMBRE.getText();
        String descripcion = TxtDESCRIPCION.getText();
        Date fechainicio = TxtFechaInicio.getDate();
        Date fechafin = TxtFechaFin.getDate();
        Empleado empleado = (Empleado) TxtEMPLEADOS.getSelectedItem();
        int empleadoID = empleado.getEmpleadoID();

        // Validamos Que No Esten Vasios:  
        
        if (nombre.trim().isEmpty()) {
            throw new IllegalArgumentException("Debe Ingresar Un Nombre");
        } else {
            proyecto.setNombre(nombre);
        }
    
        if (fechainicio==null) {
            throw new IllegalArgumentException("Debe Ingresar Una Fecha De Inicio");
        } else {
            proyecto.setFechaInicio(fechainicio);
        }

        if (fechafin==null) {
            throw new IllegalArgumentException("Debe Ingresar Una Fecha De Finalizacion");
        } else {
            proyecto.setFechaFin(fechafin);
        }
        
        proyecto.setDescripcion(descripcion);
        
        // Empleado Seleccionado:
        proyecto.setEmpledoID(empleadoID);
        
        if(opcionesCRUD!=CREAR)
        {
            proyecto.setProyectoID(ProyectoActual.getProyectoID());
        }
        return proyecto;
    }
    
    
     // CREAR NUEVO REGISTRO:
    private void CrearRegistro() 
    {
        
        try {
            // Obtenemos Objeto Con inf Del Formulario:
            Proyecto proyecto = DatosDelFormulario();

            // Creamos El Registro:           
            int result = ProyectoDAL.Crear(proyecto);

            // Mensaje De Fila Afectada
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "El Proyecto fue registrado existosamente", "REGISTRADO",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "No Se Pudo Registrar El Proyecto", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
            }
        } 
        catch (Exception Error) {
            JOptionPane.showMessageDialog(this,
                    Error.getMessage(), "HOLAAA",
                    JOptionPane.ERROR_MESSAGE);     
        }       
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCANCELAR;
    private javax.swing.JButton BtnGUARDAR;
    private javax.swing.JTextArea TxtDESCRIPCION;
    private javax.swing.JComboBox<Empleado> TxtEMPLEADOS;
    private com.toedter.calendar.JDateChooser TxtFechaFin;
    private com.toedter.calendar.JDateChooser TxtFechaInicio;
    private javax.swing.JTextField TxtNOMBRE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
