package com.mycompany.java.crud;

import Acceso_Datos.ProyectoDAL;
import Entidades.Empleado;
import Entidades.Proyecto;
import Utilerias.OpcionesCRUD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_Inicio_Proyecto extends javax.swing.JFrame {

    // CONSTRUCTOR:
    public Form_Inicio_Proyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtNOMBRE = new javax.swing.JTextField();
        BtnCREAR = new javax.swing.JButton();
        BtnBUSCAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        BtnCANCELAR = new javax.swing.JButton();
        BtnEDITAR = new javax.swing.JButton();
        BtnELIMINAR = new javax.swing.JButton();

        jLabel1.setText("NOMBRE:");

        BtnCREAR.setText("CREAR");
        BtnCREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCREARActionPerformed(evt);
            }
        });

        BtnBUSCAR.setText("BUSCAR");
        BtnBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBUSCARActionPerformed(evt);
            }
        });

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaResultados);

        BtnCANCELAR.setText("CANCELAR");
        BtnCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCANCELARActionPerformed(evt);
            }
        });

        BtnEDITAR.setText("EDITAR");
        BtnEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEDITARActionPerformed(evt);
            }
        });

        BtnELIMINAR.setText("ELIMINAR");
        BtnELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnELIMINARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCREAR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 576, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BtnEDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCREAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCANCELAR)
                    .addComponent(BtnELIMINAR)
                    .addComponent(BtnEDITAR))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*                      EVENTOS DE BOTONES
    *********************************************************************/
    // BOTON CREAR:
    private void BtnCREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCREARActionPerformed
        Form_Proyecto Formulario_Proyecto1 = new Form_Proyecto(OpcionesCRUD.CREAR, new Proyecto());
        Formulario_Proyecto1.setTitle("NUEVO REGISTRO");
        Formulario_Proyecto1.setVisible(true);
    }//GEN-LAST:event_BtnCREARActionPerformed

    // BOTON EDITAR:
    private void BtnEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEDITARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEDITARActionPerformed

    // BOTON ELIMINAR:
    private void BtnELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnELIMINARActionPerformed
        // Fila Seleccinada
        int row = TablaResultados.getSelectedRow();

        if (row != -1) {
            // LLamada Del Formulario:
            Form_Proyecto Formulario_Proyecto1 = new Form_Proyecto(OpcionesCRUD.ELIMINAR, DatosFila());
            Formulario_Proyecto1.setTitle("ELIMINAR REGISTRO");
            Formulario_Proyecto1.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Seleccionar una fila", "SELECCIONE",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnELIMINARActionPerformed

    // BOTON BUSCAR:
    private void BtnBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBUSCARActionPerformed
        // Objeto:
        Proyecto proyecto = new Proyecto();

        // Agregamos El Nombre Del Texbox Del Formulario
        proyecto.setNombre(TxtNOMBRE.getText());

        // Lista De Registros Encontrados:
        ArrayList<Proyecto> Objetos_Obtenidos = ProyectoDAL.Buscar(proyecto);

        // Nombrando Las Columnas De La Tabla:
        String[] COLUMNAS = {"ID", "NOMBRE DEL PROYECTO", "DESCRIPCION", "FECHA DE INICIO", "FECHA DE FIN", "EMPLEADO A CARGO", "ID EMPLEADO"};

        // Lista De Registros Encontrados Y Pasados A Object:
        Object[][] DATOS = new Object[Objetos_Obtenidos.size()][7];

        for (int i = 0; i < Objetos_Obtenidos.size(); i++) {
            // Registro Con Su Posicion:
            Proyecto Registro = Objetos_Obtenidos.get(i);

            // Creacion De Objeto Segun Objeto De La Posicion:
            DATOS[i][0] = Registro.getProyectoID();
            DATOS[i][1] = Registro.getNombre();
            DATOS[i][2] = Registro.getDescripcion();
            DATOS[i][3] = Registro.getFechaInicio();
            DATOS[i][4] = Registro.getFechaFin();
            DATOS[i][5] = (Registro.getObjeto_Empledo().getNombre()) + " " + (Registro.getObjeto_Empledo().getApellido());
            DATOS[i][6] = Registro.getEmpledoID();
        }

        // Agregando Los Nombres De Las Columnas Y Los Registros
        DefaultTableModel ResultadosTabla = new DefaultTableModel(DATOS, COLUMNAS);

        // Mandamos A La Tabla Del Formulario
        TablaResultados.setModel(ResultadosTabla);
    }//GEN-LAST:event_BtnBUSCARActionPerformed

    // BOTON CANCELAR:
    private void BtnCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCANCELARActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BtnCANCELARActionPerformed

    
    
    
    /*                    METODO REALIZAR CAMBIOS EN DB
    *********************************************************************/
    // CREA UN OBJETO CON TODOS LOS DATOS DE LA FILA SELECCIONADA:
    private Proyecto DatosFila() {
        // Objeto:
        Proyecto proyecto = new Proyecto();

        // Fila Seleccionada:
        int row = TablaResultados.getSelectedRow();

        // Atributos De La Fila Colocarlos En El Objeto:
        proyecto.setProyectoID((int) TablaResultados.getValueAt(row, 0));
        proyecto.setNombre(TablaResultados.getValueAt(row, 1).toString());
        proyecto.setDescripcion(TablaResultados.getValueAt(row, 2).toString());

        Object valorFechaInicio = TablaResultados.getValueAt(row, 3);
        java.util.Date fechaInicio = (java.util.Date) valorFechaInicio;
        proyecto.setFechaInicio(fechaInicio);
        
        Object valorFechaFin = TablaResultados.getValueAt(row, 4);
        java.util.Date fechaFin = (java.util.Date) valorFechaFin;
        proyecto.setFechaFin(fechaFin);
        
        proyecto.setEmpledoID((int)TablaResultados.getValueAt(row, 6));
        
        Empleado empleado = new Empleado();
        empleado.setNombre(TablaResultados.getValueAt(row, 5).toString());
        empleado.setEmpleadoID((int)TablaResultados.getValueAt(row, 6));
        proyecto.setObjeto_Empledo(empleado);
        
        return proyecto;
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Inicio_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Inicio_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Inicio_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Inicio_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Inicio_Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBUSCAR;
    private javax.swing.JButton BtnCANCELAR;
    private javax.swing.JButton BtnCREAR;
    private javax.swing.JButton BtnEDITAR;
    private javax.swing.JButton BtnELIMINAR;
    private javax.swing.JTable TablaResultados;
    private javax.swing.JTextField TxtNOMBRE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
